### ISSUE TITLE
!important in styling

### ISSUE THREAD

**Issue by ElsaTam** [justanotherjurastudent/highlight-active-folder-section#1]
Hi!
Thanks a lot for making this plugin. I was looking for something like that as it was frustrating to keep track of the active folder as soon as it was collapsed. Yours work perfectly!
I would love to support this plugin in my theme but change the styling to fit better with what I already have. However, you are using a lot of !important flags which make it a little bit hard to override. I don't know if that's intended or not. I can still override them with extra selectors, but it's not the best practice. Do you think it's doable to remove those !important?
If not, it's totally okay!
Thanks again for sharing your work :)

**Comment by justanotherjurastudent** [comment]
Hi @ElsaTam, thank you! I'm very happy that you're like my work.
I think I can do this. Honestly, !important flags are for my personal use case in relation with my border theme, which seems to overrides my PlugIn, when I don't set this flags, I guess. I have to look and reply soon!

**Comment by ElsaTam** [comment]
Oh ok! The Border theme probably already set some selectors with higher specificity.
If you want, I can try to change the styling on the Border theme and find the proper selectors that won't require the `!important`, and make a pull request.

**Comment by justanotherjurastudent** [comment]
Ah, I think I will do a new toggle in the settings. When this is activated, then the important flag are going to added or appended to the styles.

**Comment by ElsaTam** [comment]
Seems like a great idea! People will be able to choose between your, or the override of the theme.

**Comment by ElsaTam** [comment]
A huge thank you :D
