### ISSUE TITLE
Could you please add an option to adjust thickness of highlighted areas?

### ISSUE THREAD

**Issue by hyperphysin** [justanotherjurastudent/highlight-active-folder-section#4]
![Screenshot 2024-10-09 at 7 13 05 AM](https://github.com/user-attachments/assets/005d824b-447b-4255-89ed-a7eef0120785)

I think it's too thick.

**Comment by justanotherjurastudent** [comment]
Hi, the new update should "fix" that. Now, the nav-folder only has padding, when it is uncollapsed.
